@extends('layouts.datatable')
@section('styles')
    <link href="{{ asset('assets/plugins/datatable/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" />
@endsection

@section('content')
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">
            <!--breadcrumb-->
            <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                <div class="breadcrumb-title pe-3">Compliance Report Details</div>
                <div class="ps-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-0 p-0">
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.homepage') }}"><i class="bx bx-home-alt"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="{{ route('admin.compliance.index') }}">Compliance Reports</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Details</li>
                        </ol>
                    </nav>
                </div>
            </div>
            <!--end breadcrumb-->

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center">
                                <div>
                                    <h5 class="mb-0">Compliance Report #{{ $complianceReport->id }}</h5>
                                    <p class="mb-0 text-secondary">{{ ucfirst($complianceReport->report_type) }} Report</p>
                                </div>
                                <div class="ms-auto">
                                    @if($complianceReport->file_path)
                                        <a href="{{ route('admin.compliance.download', $complianceReport->id) }}" class="btn btn-primary btn-sm">
                                            <i class="bx bx-download"></i> Download Report
                                        </a>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <table class="table table-borderless">
                                        <tr>
                                            <th width="150">Report Type:</th>
                                            <td>
                                                <span class="badge bg-info">{{ ucfirst($complianceReport->report_type) }}</span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Period:</th>
                                            <td>{{ $complianceReport->period }}</td>
                                        </tr>
                                        <tr>
                                            <th>Status:</th>
                                            <td>
                                                <span class="badge bg-{{ $complianceReport->status == 'completed' ? 'success' : ($complianceReport->status == 'processing' ? 'warning' : 'danger') }}">
                                                    {{ ucfirst($complianceReport->status) }}
                                                </span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Generated By:</th>
                                            <td>{{ $complianceReport->generated_by }}</td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <table class="table table-borderless">
                                        <tr>
                                            <th width="150">Created:</th>
                                            <td>{{ $complianceReport->created_at->format('Y-m-d H:i:s') }}</td>
                                        </tr>
                                        <tr>
                                            <th>Updated:</th>
                                            <td>{{ $complianceReport->updated_at->format('Y-m-d H:i:s') }}</td>
                                        </tr>
                                        <tr>
                                            <th>File Path:</th>
                                            <td>{{ $complianceReport->file_path ?? 'No file generated' }}</td>
                                        </tr>
                                        <tr>
                                            <th>File Size:</th>
                                            <td>{{ $complianceReport->file_size ? number_format($complianceReport->file_size / 1024, 2) . ' KB' : 'N/A' }}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                            @if($complianceReport->summary)
                            <div class="row mt-4">
                                <div class="col-12">
                                    <h6>Report Summary</h6>
                                    <div class="card bg-light">
                                        <div class="card-body">
                                            <pre class="mb-0">{{ json_encode($complianceReport->summary, JSON_PRETTY_PRINT) }}</pre>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endif

                            @if($complianceReport->metadata)
                            <div class="row mt-4">
                                <div class="col-12">
                                    <h6>Report Metadata</h6>
                                    <div class="table-responsive">
                                        <table class="table table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Key</th>
                                                    <th>Value</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($complianceReport->metadata as $key => $value)
                                                    <tr>
                                                        <td><strong>{{ ucfirst(str_replace('_', ' ', $key)) }}</strong></td>
                                                        <td>{{ is_array($value) ? json_encode($value) : $value }}</td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            @endif
                        </div>
                        <div class="card-footer">
                            <a href="{{ route('admin.compliance.index') }}" class="btn btn-secondary">
                                <i class="bx bx-arrow-back"></i> Back to List
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end page wrapper -->
@endsection

@section('scripts')
@endsection 